#!/usr/bin/env python3

import sys
import re
import string

GOOSE_EMOJI = '🦢'

has_cap = lambda x: x[0] in list(chr(a) for a in range(ord('A'), ord('Z')))

LETTERS = string.ascii_letters
UPPERCASE_LETTERS = string.ascii_uppercase

def honkhonk(stream):
    i = 0
    for line in stream:
        prev_is_letter = False
        o = ""
        line = line.rstrip()
        for c in line:
            if c not in LETTERS:
                if prev_is_letter:
                    o = o[:-2] + 'nk' 
                o += c
                prev_is_letter = False
            if c in LETTERS:
                if not prev_is_letter:
                    if c in UPPERCASE_LETTERS:
                        o += 'H'
                    else:
                        o += 'h'
                else:
                    o += 'o'
                prev_is_letter = True
        print(o)

honkhonk(sys.stdin)
